name: build-keydb-container

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KEYDB_REPO: "https://github.com/Snapchat/KeyDB"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Determine latest keydb tag
        run: |
          echo "LATEST_TAG=$(git ls-remote --tags --exit-code --refs "$KEYDB_REPO" | sed -E 's/^[[:xdigit:]]+[[:space:]]+refs\/tags\/(.+)/\1/g' | tail -n1)" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v3

      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.LATEST_TAG }}
            type=raw,value=latest

      - name: Build and Push Container Image(s)
        uses: docker/build-push-action@v4
        with:
          context:
          platforms: linux/amd64  # ,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SRC_REPO=${{ env.KEYDB_REPO }}
            BRANCH=${{ env.LATEST_TAG }}
